error: log asserts and int3s
At least int3 calls seem to be in reachable but unlikely code paths as
well. So instead of crashing, just make it log. I assume when they were
developing this, int3 didn't make it crash even in debug mode, but
dropped it into the debugger or just continued.